# Server Configuration
server:
  port: 8080
  servlet:
    context-path: /user-service


# Spring Application Settings
spring:
  application:
    name: user-service

  ## Database (MySQL) Configuration
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${DB_HOST}/${MYSQL_DATABASE}?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC&useUnicode=true&characterEncoding=UTF-8
    username: ${MYSQL_USER}
    password: ${MYSQL_PASSWORD}

  ## JPA / Hibernate Configuration
  jpa:
    hibernate:
      ddl-auto: ${JPA_DDL_AUTO}
    show-sql: ${JPA_SHOW_SQL}
    properties:
      hibernate:
        format_sql: ${JPA_FORMAT_SQL}
  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}

  kafka:
    bootstrap-servers: ${SPRING_KAFKA_BOOTSTRAP_SERVERS}
    consumer: # Consumer 설정 (auth-service로부터 요청을 받기 위함)
      bootstrap-servers: ${SPRING_KAFKA_CONSUMER_BOOTSTRAP_SERVERS}
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "com.example.commonmodule.dto.event"
        spring.json.type.mapping: "com.example.commonmodule.dto.event.UserRegistrationRequestedEvent:com.example.commonmodule.dto.event.UserRegistrationRequestedEvent"
    producer: # Producer 설정 (auth-service로 응답을 보내기 위함)
      bootstrap-servers: ${SPRING_KAFKA_PRODUCER_BOOTSTRAP_SERVERS}
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

# gRPC Configuration
grpc:
  server:
    port: -1
  client:
    order-service:
      address: '${GRPC_CLIENT_ORDER_SERVICE_ADDRESS:static://localhost:9099}'
      enableKeepAlive: true
      negotiationType: PLAINTEXT

app:
  frontend:
    redirect-url: http://127.0.0.1:5173/auth/callback # 프론트엔드 주소


springdoc:
  override-with-generic-response: false