# Server Configuration
server:
  port: 8080
  servlet:
    context-path: /user-service


# Spring Application Settings
spring:
  application:
    name: user-service

  ## Database (MySQL) Configuration
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${DB_HOST}/${MYSQL_DATABASE}?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC&useUnicode=true&characterEncoding=UTF-8
    username: ${MYSQL_USER}
    password: ${MYSQL_PASSWORD}

  ## JPA / Hibernate Configuration
  jpa:
    hibernate:
      ddl-auto: ${JPA_DDL_AUTO}
    show-sql: ${JPA_SHOW_SQL}
    properties:
      hibernate:
        format_sql: ${JPA_FORMAT_SQL}
  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}

  kafka:
    bootstrap-servers: ${SPRING_KAFKA_BOOTSTRAP_SERVERS}
    consumer:
      bootstrap-servers: ${SPRING_KAFKA_CONSUMER_BOOTSTRAP_SERVERS}
      key-deserializer: io.confluent.kafka.serializers.KafkaAvroDeserializer
      value-deserializer: io.confluent.kafka.serializers.KafkaAvroDeserializer
      group-id: "user-profile-consumer"
      properties:
        schema.registry.url: http://10.0.2.9:8081
        specific.avro.reader: false

# gRPC Configuration
grpc:
  server:
    port: -1
  client:
    order-service:
      address: '${GRPC_CLIENT_ORDER_SERVICE_ADDRESS:static://localhost:9099}'
      enableKeepAlive: true
      negotiationType: PLAINTEXT

app:
  frontend:
    redirect-url: http://127.0.0.1:5173/auth/callback # 프론트엔드 주소


springdoc:
  override-with-generic-response: false

# --- Monitoring Configuration (Added) ---
management:
  endpoints:
    web:
      exposure:
        include: prometheus, health, info  # 프로메테우스 지표 노출 허용
  endpoint:
    health:
      show-details: always
    prometheus:
      enabled: true
  metrics:
    tags:
      application: ${spring.application.name} # Grafana에서 서비스별로 구분하기 위해 태그 추가