server:
  port: 8083
  servlet:
    context-path: /chat-service

spring:
  main:
    web-application-type: reactive # WebFlux ??
  application:
    name: chat-service

  # --- MongoDB Configuration ---
  data:
    mongodb:
      authentication-database: ${MONGO_ROOT_USERNAME}
      username: ${MONGO_ROOT_USERNAME}
      password: ${MONGO_ROOT_PASSWORD}
      database: ${MONGO_DATABASE}
      host: ${SPRING_DATA_MONGODB_HOST}
      port: ${SPRING_DATA_MONGODB_PORT}

    # --- Redis Configuration ---
    redis:
      host: ${SPRING_DATA_REDIS_HOST}
      port: ${SPRING_DATA_REDIS_PORT}


# --- Feign Client Configuration (for User Profile Lookup) ---
app:
  feign:
    user-service-url: http://user-service:80 # k8s ?? ??? ??