server:
  port: 8083
  servlet:
    context-path: /chat-service

spring:
  application:
    name: chat-service

  # MongoDB (K8s ?? ?? ?? ConfigMap ??)
  data:
    mongodb:
      host: ${SPRING_DATA_MONGODB_HOST}
      port: ${SPRING_DATA_MONGODB_PORT}
      database: ${SPRING_DATA_MONGODB_DATABASE}
      authentication-database: ${SPRING_DATA_MONGODB_AUTHENTICATION_DATABASE}
      username: ${MONGO_INITDB_ROOT_USERNAME}
      password: ${MONGO_INITDB_ROOT_PASSWORD}

  # Redis (Pub/Sub)
    redis:
      host: ${SPRING_DATA_REDIS_HOST}
      port: ${SPRING_DATA_REDIS_PORT}

  # Feign Client
  cloud:
    openfeign:
      client:
        config:
          default:
            connectTimeout: 5000
            readTimeout: 5000

# K8s Service DNS
app:
  feign:
    user-service-url: http://user-service:80

logging:
  level:
    org.springframework.web.socket: DEBUG
    com.example.chatservice: DEBUG