server:
  port: 8084
  servlet:
    context-path: support-service

spring:
  application:
    name: support-service

  # DB ?? (MySQL)
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${DB_HOST}/${MYSQL_DATABASE}?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC&useUnicode=true&characterEncoding=UTF-8
    username: ${MYSQL_USER}
    password: ${MYSQL_PASSWORD}

  # JPA ??
  jpa:
    hibernate:
      ddl-auto: ${JPA_DDL_AUTO}
    show-sql: ${JPA_SHOW_SQL}
    properties:
      hibernate:
        format_sql: ${JPA_FORMAT_SQL}

  # Redis ??
  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}

# Swagger ??
springdoc:
  override-with-generic-response: false